#!/bin/sh

if [ ! -f client.exec ]; then
    echo "Please compile the program by 'make' first"
    return
fi

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/yilin/Graduate/cs557/thrift-0.9.2/lib
./client.exec $@


