/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef fileservice_CONSTANTS_H
#define fileservice_CONSTANTS_H

#include "fileservice_types.h"



class fileserviceConstants {
 public:
  fileserviceConstants();

};

extern const fileserviceConstants g_fileservice_constants;



#endif
