/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef FileStore_H
#define FileStore_H

#include <thrift/TDispatchProcessor.h>
#include "fileservice_types.h"



class FileStoreIf {
 public:
  virtual ~FileStoreIf() {}
  virtual void listOwnedFiles(std::vector<RFileMetadata> & _return, const UserID& user) = 0;
  virtual void writeFile(StatusReport& _return, const RFile& rFile) = 0;
  virtual void readFile(RFile& _return, const std::string& filename, const UserID& owner) = 0;
  virtual void deleteFile(StatusReport& _return, const std::string& filename, const UserID& owner) = 0;
};

class FileStoreIfFactory {
 public:
  typedef FileStoreIf Handler;

  virtual ~FileStoreIfFactory() {}

  virtual FileStoreIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(FileStoreIf* /* handler */) = 0;
};

class FileStoreIfSingletonFactory : virtual public FileStoreIfFactory {
 public:
  FileStoreIfSingletonFactory(const boost::shared_ptr<FileStoreIf>& iface) : iface_(iface) {}
  virtual ~FileStoreIfSingletonFactory() {}

  virtual FileStoreIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(FileStoreIf* /* handler */) {}

 protected:
  boost::shared_ptr<FileStoreIf> iface_;
};

class FileStoreNull : virtual public FileStoreIf {
 public:
  virtual ~FileStoreNull() {}
  void listOwnedFiles(std::vector<RFileMetadata> & /* _return */, const UserID& /* user */) {
    return;
  }
  void writeFile(StatusReport& /* _return */, const RFile& /* rFile */) {
    return;
  }
  void readFile(RFile& /* _return */, const std::string& /* filename */, const UserID& /* owner */) {
    return;
  }
  void deleteFile(StatusReport& /* _return */, const std::string& /* filename */, const UserID& /* owner */) {
    return;
  }
};

typedef struct _FileStore_listOwnedFiles_args__isset {
  _FileStore_listOwnedFiles_args__isset() : user(false) {}
  bool user :1;
} _FileStore_listOwnedFiles_args__isset;

class FileStore_listOwnedFiles_args {
 public:

  static const char* ascii_fingerprint; // = "EFB929595D312AC8F305D5A794CFEDA1";
  static const uint8_t binary_fingerprint[16]; // = {0xEF,0xB9,0x29,0x59,0x5D,0x31,0x2A,0xC8,0xF3,0x05,0xD5,0xA7,0x94,0xCF,0xED,0xA1};

  FileStore_listOwnedFiles_args(const FileStore_listOwnedFiles_args&);
  FileStore_listOwnedFiles_args& operator=(const FileStore_listOwnedFiles_args&);
  FileStore_listOwnedFiles_args() : user() {
  }

  virtual ~FileStore_listOwnedFiles_args() throw();
  UserID user;

  _FileStore_listOwnedFiles_args__isset __isset;

  void __set_user(const UserID& val);

  bool operator == (const FileStore_listOwnedFiles_args & rhs) const
  {
    if (!(user == rhs.user))
      return false;
    return true;
  }
  bool operator != (const FileStore_listOwnedFiles_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const FileStore_listOwnedFiles_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const FileStore_listOwnedFiles_args& obj);
};


class FileStore_listOwnedFiles_pargs {
 public:

  static const char* ascii_fingerprint; // = "EFB929595D312AC8F305D5A794CFEDA1";
  static const uint8_t binary_fingerprint[16]; // = {0xEF,0xB9,0x29,0x59,0x5D,0x31,0x2A,0xC8,0xF3,0x05,0xD5,0xA7,0x94,0xCF,0xED,0xA1};


  virtual ~FileStore_listOwnedFiles_pargs() throw();
  const UserID* user;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const FileStore_listOwnedFiles_pargs& obj);
};

typedef struct _FileStore_listOwnedFiles_result__isset {
  _FileStore_listOwnedFiles_result__isset() : success(false), systemException(false) {}
  bool success :1;
  bool systemException :1;
} _FileStore_listOwnedFiles_result__isset;

class FileStore_listOwnedFiles_result {
 public:

  static const char* ascii_fingerprint; // = "9E4A776F353C761672876B277EBDD5CD";
  static const uint8_t binary_fingerprint[16]; // = {0x9E,0x4A,0x77,0x6F,0x35,0x3C,0x76,0x16,0x72,0x87,0x6B,0x27,0x7E,0xBD,0xD5,0xCD};

  FileStore_listOwnedFiles_result(const FileStore_listOwnedFiles_result&);
  FileStore_listOwnedFiles_result& operator=(const FileStore_listOwnedFiles_result&);
  FileStore_listOwnedFiles_result() {
  }

  virtual ~FileStore_listOwnedFiles_result() throw();
  std::vector<RFileMetadata>  success;
  SystemException systemException;

  _FileStore_listOwnedFiles_result__isset __isset;

  void __set_success(const std::vector<RFileMetadata> & val);

  void __set_systemException(const SystemException& val);

  bool operator == (const FileStore_listOwnedFiles_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(systemException == rhs.systemException))
      return false;
    return true;
  }
  bool operator != (const FileStore_listOwnedFiles_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const FileStore_listOwnedFiles_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const FileStore_listOwnedFiles_result& obj);
};

typedef struct _FileStore_listOwnedFiles_presult__isset {
  _FileStore_listOwnedFiles_presult__isset() : success(false), systemException(false) {}
  bool success :1;
  bool systemException :1;
} _FileStore_listOwnedFiles_presult__isset;

class FileStore_listOwnedFiles_presult {
 public:

  static const char* ascii_fingerprint; // = "9E4A776F353C761672876B277EBDD5CD";
  static const uint8_t binary_fingerprint[16]; // = {0x9E,0x4A,0x77,0x6F,0x35,0x3C,0x76,0x16,0x72,0x87,0x6B,0x27,0x7E,0xBD,0xD5,0xCD};


  virtual ~FileStore_listOwnedFiles_presult() throw();
  std::vector<RFileMetadata> * success;
  SystemException systemException;

  _FileStore_listOwnedFiles_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

  friend std::ostream& operator<<(std::ostream& out, const FileStore_listOwnedFiles_presult& obj);
};

typedef struct _FileStore_writeFile_args__isset {
  _FileStore_writeFile_args__isset() : rFile(false) {}
  bool rFile :1;
} _FileStore_writeFile_args__isset;

class FileStore_writeFile_args {
 public:

  static const char* ascii_fingerprint; // = "822AC0906CAA16CCAF844BAA847740EA";
  static const uint8_t binary_fingerprint[16]; // = {0x82,0x2A,0xC0,0x90,0x6C,0xAA,0x16,0xCC,0xAF,0x84,0x4B,0xAA,0x84,0x77,0x40,0xEA};

  FileStore_writeFile_args(const FileStore_writeFile_args&);
  FileStore_writeFile_args& operator=(const FileStore_writeFile_args&);
  FileStore_writeFile_args() {
  }

  virtual ~FileStore_writeFile_args() throw();
  RFile rFile;

  _FileStore_writeFile_args__isset __isset;

  void __set_rFile(const RFile& val);

  bool operator == (const FileStore_writeFile_args & rhs) const
  {
    if (!(rFile == rhs.rFile))
      return false;
    return true;
  }
  bool operator != (const FileStore_writeFile_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const FileStore_writeFile_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const FileStore_writeFile_args& obj);
};


class FileStore_writeFile_pargs {
 public:

  static const char* ascii_fingerprint; // = "822AC0906CAA16CCAF844BAA847740EA";
  static const uint8_t binary_fingerprint[16]; // = {0x82,0x2A,0xC0,0x90,0x6C,0xAA,0x16,0xCC,0xAF,0x84,0x4B,0xAA,0x84,0x77,0x40,0xEA};


  virtual ~FileStore_writeFile_pargs() throw();
  const RFile* rFile;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const FileStore_writeFile_pargs& obj);
};

typedef struct _FileStore_writeFile_result__isset {
  _FileStore_writeFile_result__isset() : success(false), systemException(false) {}
  bool success :1;
  bool systemException :1;
} _FileStore_writeFile_result__isset;

class FileStore_writeFile_result {
 public:

  static const char* ascii_fingerprint; // = "3FF585046B57CAB37B1AE9B1FE6EDD6F";
  static const uint8_t binary_fingerprint[16]; // = {0x3F,0xF5,0x85,0x04,0x6B,0x57,0xCA,0xB3,0x7B,0x1A,0xE9,0xB1,0xFE,0x6E,0xDD,0x6F};

  FileStore_writeFile_result(const FileStore_writeFile_result&);
  FileStore_writeFile_result& operator=(const FileStore_writeFile_result&);
  FileStore_writeFile_result() {
  }

  virtual ~FileStore_writeFile_result() throw();
  StatusReport success;
  SystemException systemException;

  _FileStore_writeFile_result__isset __isset;

  void __set_success(const StatusReport& val);

  void __set_systemException(const SystemException& val);

  bool operator == (const FileStore_writeFile_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(systemException == rhs.systemException))
      return false;
    return true;
  }
  bool operator != (const FileStore_writeFile_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const FileStore_writeFile_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const FileStore_writeFile_result& obj);
};

typedef struct _FileStore_writeFile_presult__isset {
  _FileStore_writeFile_presult__isset() : success(false), systemException(false) {}
  bool success :1;
  bool systemException :1;
} _FileStore_writeFile_presult__isset;

class FileStore_writeFile_presult {
 public:

  static const char* ascii_fingerprint; // = "3FF585046B57CAB37B1AE9B1FE6EDD6F";
  static const uint8_t binary_fingerprint[16]; // = {0x3F,0xF5,0x85,0x04,0x6B,0x57,0xCA,0xB3,0x7B,0x1A,0xE9,0xB1,0xFE,0x6E,0xDD,0x6F};


  virtual ~FileStore_writeFile_presult() throw();
  StatusReport* success;
  SystemException systemException;

  _FileStore_writeFile_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

  friend std::ostream& operator<<(std::ostream& out, const FileStore_writeFile_presult& obj);
};

typedef struct _FileStore_readFile_args__isset {
  _FileStore_readFile_args__isset() : filename(false), owner(false) {}
  bool filename :1;
  bool owner :1;
} _FileStore_readFile_args__isset;

class FileStore_readFile_args {
 public:

  static const char* ascii_fingerprint; // = "07A9615F837F7D0A952B595DD3020972";
  static const uint8_t binary_fingerprint[16]; // = {0x07,0xA9,0x61,0x5F,0x83,0x7F,0x7D,0x0A,0x95,0x2B,0x59,0x5D,0xD3,0x02,0x09,0x72};

  FileStore_readFile_args(const FileStore_readFile_args&);
  FileStore_readFile_args& operator=(const FileStore_readFile_args&);
  FileStore_readFile_args() : filename(), owner() {
  }

  virtual ~FileStore_readFile_args() throw();
  std::string filename;
  UserID owner;

  _FileStore_readFile_args__isset __isset;

  void __set_filename(const std::string& val);

  void __set_owner(const UserID& val);

  bool operator == (const FileStore_readFile_args & rhs) const
  {
    if (!(filename == rhs.filename))
      return false;
    if (!(owner == rhs.owner))
      return false;
    return true;
  }
  bool operator != (const FileStore_readFile_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const FileStore_readFile_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const FileStore_readFile_args& obj);
};


class FileStore_readFile_pargs {
 public:

  static const char* ascii_fingerprint; // = "07A9615F837F7D0A952B595DD3020972";
  static const uint8_t binary_fingerprint[16]; // = {0x07,0xA9,0x61,0x5F,0x83,0x7F,0x7D,0x0A,0x95,0x2B,0x59,0x5D,0xD3,0x02,0x09,0x72};


  virtual ~FileStore_readFile_pargs() throw();
  const std::string* filename;
  const UserID* owner;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const FileStore_readFile_pargs& obj);
};

typedef struct _FileStore_readFile_result__isset {
  _FileStore_readFile_result__isset() : success(false), systemException(false) {}
  bool success :1;
  bool systemException :1;
} _FileStore_readFile_result__isset;

class FileStore_readFile_result {
 public:

  static const char* ascii_fingerprint; // = "3EA130E3D3BEF0C184CE2057A8221B3A";
  static const uint8_t binary_fingerprint[16]; // = {0x3E,0xA1,0x30,0xE3,0xD3,0xBE,0xF0,0xC1,0x84,0xCE,0x20,0x57,0xA8,0x22,0x1B,0x3A};

  FileStore_readFile_result(const FileStore_readFile_result&);
  FileStore_readFile_result& operator=(const FileStore_readFile_result&);
  FileStore_readFile_result() {
  }

  virtual ~FileStore_readFile_result() throw();
  RFile success;
  SystemException systemException;

  _FileStore_readFile_result__isset __isset;

  void __set_success(const RFile& val);

  void __set_systemException(const SystemException& val);

  bool operator == (const FileStore_readFile_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(systemException == rhs.systemException))
      return false;
    return true;
  }
  bool operator != (const FileStore_readFile_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const FileStore_readFile_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const FileStore_readFile_result& obj);
};

typedef struct _FileStore_readFile_presult__isset {
  _FileStore_readFile_presult__isset() : success(false), systemException(false) {}
  bool success :1;
  bool systemException :1;
} _FileStore_readFile_presult__isset;

class FileStore_readFile_presult {
 public:

  static const char* ascii_fingerprint; // = "3EA130E3D3BEF0C184CE2057A8221B3A";
  static const uint8_t binary_fingerprint[16]; // = {0x3E,0xA1,0x30,0xE3,0xD3,0xBE,0xF0,0xC1,0x84,0xCE,0x20,0x57,0xA8,0x22,0x1B,0x3A};


  virtual ~FileStore_readFile_presult() throw();
  RFile* success;
  SystemException systemException;

  _FileStore_readFile_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

  friend std::ostream& operator<<(std::ostream& out, const FileStore_readFile_presult& obj);
};

typedef struct _FileStore_deleteFile_args__isset {
  _FileStore_deleteFile_args__isset() : filename(false), owner(false) {}
  bool filename :1;
  bool owner :1;
} _FileStore_deleteFile_args__isset;

class FileStore_deleteFile_args {
 public:

  static const char* ascii_fingerprint; // = "07A9615F837F7D0A952B595DD3020972";
  static const uint8_t binary_fingerprint[16]; // = {0x07,0xA9,0x61,0x5F,0x83,0x7F,0x7D,0x0A,0x95,0x2B,0x59,0x5D,0xD3,0x02,0x09,0x72};

  FileStore_deleteFile_args(const FileStore_deleteFile_args&);
  FileStore_deleteFile_args& operator=(const FileStore_deleteFile_args&);
  FileStore_deleteFile_args() : filename(), owner() {
  }

  virtual ~FileStore_deleteFile_args() throw();
  std::string filename;
  UserID owner;

  _FileStore_deleteFile_args__isset __isset;

  void __set_filename(const std::string& val);

  void __set_owner(const UserID& val);

  bool operator == (const FileStore_deleteFile_args & rhs) const
  {
    if (!(filename == rhs.filename))
      return false;
    if (!(owner == rhs.owner))
      return false;
    return true;
  }
  bool operator != (const FileStore_deleteFile_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const FileStore_deleteFile_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const FileStore_deleteFile_args& obj);
};


class FileStore_deleteFile_pargs {
 public:

  static const char* ascii_fingerprint; // = "07A9615F837F7D0A952B595DD3020972";
  static const uint8_t binary_fingerprint[16]; // = {0x07,0xA9,0x61,0x5F,0x83,0x7F,0x7D,0x0A,0x95,0x2B,0x59,0x5D,0xD3,0x02,0x09,0x72};


  virtual ~FileStore_deleteFile_pargs() throw();
  const std::string* filename;
  const UserID* owner;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const FileStore_deleteFile_pargs& obj);
};

typedef struct _FileStore_deleteFile_result__isset {
  _FileStore_deleteFile_result__isset() : success(false), systemException(false) {}
  bool success :1;
  bool systemException :1;
} _FileStore_deleteFile_result__isset;

class FileStore_deleteFile_result {
 public:

  static const char* ascii_fingerprint; // = "3FF585046B57CAB37B1AE9B1FE6EDD6F";
  static const uint8_t binary_fingerprint[16]; // = {0x3F,0xF5,0x85,0x04,0x6B,0x57,0xCA,0xB3,0x7B,0x1A,0xE9,0xB1,0xFE,0x6E,0xDD,0x6F};

  FileStore_deleteFile_result(const FileStore_deleteFile_result&);
  FileStore_deleteFile_result& operator=(const FileStore_deleteFile_result&);
  FileStore_deleteFile_result() {
  }

  virtual ~FileStore_deleteFile_result() throw();
  StatusReport success;
  SystemException systemException;

  _FileStore_deleteFile_result__isset __isset;

  void __set_success(const StatusReport& val);

  void __set_systemException(const SystemException& val);

  bool operator == (const FileStore_deleteFile_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(systemException == rhs.systemException))
      return false;
    return true;
  }
  bool operator != (const FileStore_deleteFile_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const FileStore_deleteFile_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const FileStore_deleteFile_result& obj);
};

typedef struct _FileStore_deleteFile_presult__isset {
  _FileStore_deleteFile_presult__isset() : success(false), systemException(false) {}
  bool success :1;
  bool systemException :1;
} _FileStore_deleteFile_presult__isset;

class FileStore_deleteFile_presult {
 public:

  static const char* ascii_fingerprint; // = "3FF585046B57CAB37B1AE9B1FE6EDD6F";
  static const uint8_t binary_fingerprint[16]; // = {0x3F,0xF5,0x85,0x04,0x6B,0x57,0xCA,0xB3,0x7B,0x1A,0xE9,0xB1,0xFE,0x6E,0xDD,0x6F};


  virtual ~FileStore_deleteFile_presult() throw();
  StatusReport* success;
  SystemException systemException;

  _FileStore_deleteFile_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

  friend std::ostream& operator<<(std::ostream& out, const FileStore_deleteFile_presult& obj);
};

class FileStoreClient : virtual public FileStoreIf {
 public:
  FileStoreClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  FileStoreClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void listOwnedFiles(std::vector<RFileMetadata> & _return, const UserID& user);
  void send_listOwnedFiles(const UserID& user);
  void recv_listOwnedFiles(std::vector<RFileMetadata> & _return);
  void writeFile(StatusReport& _return, const RFile& rFile);
  void send_writeFile(const RFile& rFile);
  void recv_writeFile(StatusReport& _return);
  void readFile(RFile& _return, const std::string& filename, const UserID& owner);
  void send_readFile(const std::string& filename, const UserID& owner);
  void recv_readFile(RFile& _return);
  void deleteFile(StatusReport& _return, const std::string& filename, const UserID& owner);
  void send_deleteFile(const std::string& filename, const UserID& owner);
  void recv_deleteFile(StatusReport& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class FileStoreProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<FileStoreIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (FileStoreProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_listOwnedFiles(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_writeFile(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_readFile(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_deleteFile(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  FileStoreProcessor(boost::shared_ptr<FileStoreIf> iface) :
    iface_(iface) {
    processMap_["listOwnedFiles"] = &FileStoreProcessor::process_listOwnedFiles;
    processMap_["writeFile"] = &FileStoreProcessor::process_writeFile;
    processMap_["readFile"] = &FileStoreProcessor::process_readFile;
    processMap_["deleteFile"] = &FileStoreProcessor::process_deleteFile;
  }

  virtual ~FileStoreProcessor() {}
};

class FileStoreProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  FileStoreProcessorFactory(const ::boost::shared_ptr< FileStoreIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< FileStoreIfFactory > handlerFactory_;
};

class FileStoreMultiface : virtual public FileStoreIf {
 public:
  FileStoreMultiface(std::vector<boost::shared_ptr<FileStoreIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~FileStoreMultiface() {}
 protected:
  std::vector<boost::shared_ptr<FileStoreIf> > ifaces_;
  FileStoreMultiface() {}
  void add(boost::shared_ptr<FileStoreIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void listOwnedFiles(std::vector<RFileMetadata> & _return, const UserID& user) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->listOwnedFiles(_return, user);
    }
    ifaces_[i]->listOwnedFiles(_return, user);
    return;
  }

  void writeFile(StatusReport& _return, const RFile& rFile) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->writeFile(_return, rFile);
    }
    ifaces_[i]->writeFile(_return, rFile);
    return;
  }

  void readFile(RFile& _return, const std::string& filename, const UserID& owner) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->readFile(_return, filename, owner);
    }
    ifaces_[i]->readFile(_return, filename, owner);
    return;
  }

  void deleteFile(StatusReport& _return, const std::string& filename, const UserID& owner) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->deleteFile(_return, filename, owner);
    }
    ifaces_[i]->deleteFile(_return, filename, owner);
    return;
  }

};



#endif
